### ISSUE TITLE
Add Main-Action Event to all slides

### ISSUE THREAD

**Issue by holycrossav** [kjgriffin/LivestreamServiceSuite#19]
We can do pre/post events with dedicated action slides/ autoseq action slides. Would like a way to execute actions on all slide types. E.g. for a hymn - put the next camera shot (preset source) as a main action so when the slide shows hymn we can have an automated preset for next shot. This is better than having the next slide be a dedicate action. This also allows a large set of liturgy slides to have automated camera transitions.

**Comment by kjgriffin** [comment]
WIP implementation on ActionsForAll branch

**Comment by kjgriffin** [comment]
For now we will handle this feature with Postset. Should handle the main use case.
For something like performing an action after a video has played, we will consider having another (less general purpose) method to accomplish something like that in the future as needs warrant.

**Comment by kjgriffin** [comment]
1.7.1 - postset feature considered to implement the majority of use cases for actions on all slides.
