### ISSUE TITLE
Change Default Config to have VU Meter Disabled

### ISSUE THREAD

**Issue by holycrossav** [kjgriffin/LivestreamServiceSuite#20]
https://github.com/kjgriffin/LivestreamServiceSuite/blob/63c1b8b032a144d79d3c45d79c24c9aa38931376/Integrated%20Presenter/BMDSwitcher/BMDSwitcherManager.cs#L852

// window, enabled
_BMDSwitcherMultiView.SetVuMeterEnabled(0, false);
_BMDSwitcherMultiView.SetVuMeterEnabled(1, false);
_BMDSwitcherMultiView.SetVuMeterEnabled(2, false);
_BMDSwitcherMultiView.SetVuMeterEnabled(3, false);
_BMDSwitcherMultiView.SetVuMeterEnabled(4, false);
_BMDSwitcherMultiView.SetVuMeterEnabled(5, false);
_BMDSwitcherMultiView.SetVuMeterEnabled(6, false);
_BMDSwitcherMultiView.SetVuMeterEnabled(7, false);
_BMDSwitcherMultiView.SetVuMeterEnabled(8, false);

**Comment by kjgriffin** [comment]
Candidate fix in commit: 5aa0f41f

**Comment by holycrossav** [comment]
fixed build 1.6.2.2

**Comment by kjgriffin** [comment]
Validated Fix
